name: "ctag esp idf build"
description: "This action build your firmware directly in github using Espressif esp idf."
branding:
  color: blue
  icon: check
outputs:
  build_output:
    description: "Output of the idf.py build command."
runs:
  using: "docker"
  image: "Dockerfile"
