name: "ctag esp idf build"
description: "This action build your firmware directly in github using Espressif esp idf."
branding:
  color: blue
  icon: check
runs:
  using: "docker"
  image: "Dockerfile"